routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth','role:admin']], function () {
    Route::get('/dashboard','DashboardController@index')->name('dashboard.admin');

    Route::get('/dashboard/produk','ProductController@index')->name('produk.admin');
    Route::get('/dashboard/produk/cari','ProductController@cari')->name('cariproduk.admin');
    Route::get('/dashboard/produk/tambah','ProductController@tambahForm')->name('tampiltambah.admin');
    Route::post('/dashboard/produk/tambah','ProductController@tambahProduk')->name('tambahproduk.admin');
    Route::get('/dashboard/produk/ubah/{slug}','ProductController@editForm')->name('tampilubahproduk.admin');
    Route::post('/dashboard/produk/ubah/{slug}','ProductController@updateProduk')->name('updateproduk.admin');
    Route::delete('/dashboard/produk/hapus/{slug}','ProductController@hapusProduk')->name('hapusproduk.admin');
    Route::get('/dashboard/produk/detail/{slug}','ProductController@detailProduk')->name('detailproduk.admin');

    Route::get('/dashboard/kategori','CategoryController@index')->name('tampilkategori.admin');
    Route::post('/dashboard/kategori/tambah','CategoryController@tambahCategory')->name('tambahkategori.admin');
    Route::get('/dashboard/kategori/ubah/{slug}','CategoryController@editForm')->name('tampilubahkategori.admin');
    Route::post('/dashboard/kategori/ubah/{slug}','CategoryController@updateCategory')->name('updatekategori.admin');
    Route::delete('/dashboard/kategori/hapus/{slug}','CategoryController@hapusCategory')->name('hapuskategori.admin');

    Route::get('/dashboard/kategori-layanan','CategoryLayananController@index')->name('tampilkategorilayanan.admin');
    Route::post('/dashboard/kategori-layanan/tambah','CategoryLayananController@tambahCategoryLayanan')->name('tambahkategorilayanan.admin');
    Route::get('/dashboard/kategori-layanan/ubah/{slug}','CategoryLayananController@editFormLayanan')->name('tampilubahkategorilayanan.admin');
    Route::post('/dashboard/kategori-layanan/ubah/{slug}','CategoryLayananController@updateCategoryLayanan')->name('updatekategorilayanan.admin');
    Route::delete('/dashboard/kategori-layanan/hapus/{slug}','CategoryLayananController@hapusCategoryLayanan')->name('hapuskategorilayanan.admin');

    
    Route::get('/dashboard/layanan','LayananController@index')->name('layanan.admin');
    Route::get('/dashboard/layanan/cari','LayananController@cari')->name('carilayanan.admin');
    Route::get('/dashboard/layanan/tambah','LayananController@tambahForm')->name('tampiltambahlayanan.admin');
    Route::post('/dashboard/layanan/tambah','LayananController@tambahLayanan')->name('tambahlayanan.admin');
    Route::get('/dashboard/layanan/ubah/{slug}','LayananController@editForm')->name('tampilubahlayanan.admin');
    Route::post('/dashboard/layanan/ubah/{slug}','LayananController@updateLayanan')->name('updatelayanan.admin');
    Route::delete('/dashboard/layanan/hapus/{slug}','LayananController@hapusLayanan')->name('hapuslayanan.admin');
    Route::get('/dashboard/layanan/detail/{slug}','LayananController@detailLayanan')->name('detaillayanan.admin');


    Route::get('/dashboard/pengguna/cari','UserController@cari')->name('cariuser.admin');
    Route::get('/dashboard/pengguna','UserController@index')->name('user.admin');
    Route::get('/dashboard/pengguna/detail/{slug}','UserController@detailUser')->name('detailuser.admin');
    Route::get('/dashboard/pengguna/tambah','UserController@tampilForm')->name('tampiltambahpengguna.admin');
    Route::post('/dashboard/pengguna/tambah','UserController@tambahPengguna')->name('tambahpengguna.admin');

    Route::get('/dashboard/pemesanan','OrderController@index')->name('pemesanan.admin');
    Route::get('/dashboard/pemesanan/{slug}','OrderController@detail')->name('pemesananDetail.admin');
    Route::get('/dashboard/pemesanan/terima/{slug}','OrderController@terima')->name('pemesanan.terima');
    Route::get('/dashboard/report', 'reportController@index')->name('pemesanan.report');


    Route::get('/dashboard/reservasi','ReservasiController@index')->name('tampilreservasi.admin');
    Route::get('/dashboard/reservasi/tambah','ReservasiController@tambahForm')->name('tampiltambahreservasi.admin');
    Route::post('/dashboard/reservasi/tambah','ReservasiController@tambahReservasi')->name('tambahreservasi.admin');
    Route::get('/dashboard/reservasi/ubah/{id}','ReservasiController@editForm')->name('tampilubahreservasi.admin');
    Route::post('/dashboard/reservasi/ubah/{id}','ReservasiController@updateReservasi')->name('updatereservasi.admin');
    Route::get('/dashboard/reservasi/detail/{id}','ReservasiController@detailReservasi')->name('detailreservasi.admin');
    Route::get('/dashboard/reservasi/hapus/{id}','ReservasiController@hapusReservasi')->name('hapusreservasi.admin');
    Route::get('/dashboard/reservasi/report','ReservasiController@reportReservasi')->name('reportreservasi.admin');

});

Route::group(['middleware' => ['auth','role:user']], function () {
    Route::post('/keranjang/{slug}','CartController@order')->name('tambahkeranjang.index');
    Route::delete('/keranjang/{slug}','CartController@hapusKeranjang')->name('hapuskeranjang.index');

    Route::get('/riwayat','HistoryController@index')->name('history.index');
    Route::get('/riwayat/{slug}','HistoryController@detail')->name('historydetail.index');

    Route::get('/checkout','OrderController@tampilCheckout')->name('tampilcheckout.index');
    Route::post('/checkout/selesai','OrderController@checkout')->name('checkout.index');

    Route::get('/profil','UserController@profile')->name('profile.index');
    Route::post('/profil','UserController@updateProfile')->name('updateprofile.index');

    Route::post('/uploadtransfer/{slug}','bayarController@upload');
});

Route::get('/','HomeController@index')->name('home.index');
Route::get('/tentangkami','AboutController@index')->name('about.index');

Route::get('/produk','HomeController@produk')->name('produk.index');
Route::get('/produk/cari','HomeController@cari')->name('cariproduk.index');
Route::get('/produk/kategori/{slug}','HomeController@kategori')->name('produkkategori.index');
Route::get('/produk/{slug}','HomeController@show')->name('detailproduk.index');

Route::get('/layanan','LayananHomeController@layanan')->name('layanan.index');
Route::get('/layanan/cari','LayananHomeController@cari')->name('carilayanan.index');
Route::get('/layanan/{slug}','LayananHomeController@show')->name('detaillayanan.index');
Route::get('/layanan/kategori/{slug}','LayananHomeController@kategori')->name('layanankategori.index');

Route::get('/keranjang','CartController@keranjang')->name('keranjang.index');

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Category;


class HomeController extends Controller
{
    public function index(Request $request)
    {

        $produk = Product::all()->take(8);
        $kategori = Category::all();

        return view('home.index',compact('produk','kategori'));
    }

    public function produk()
    {
        $produk =  Product::orderBy('created_at','desc')->paginate(12);
        $kategori = Category::withCount('product')->get();


        return view('produk.index',compact('produk','kategori'));
    }

    public function show($slug)
    {
        $produk = Product::where('slug',$slug)->first();

        return view('produk.detail', compact('produk'));
    }

    public function kategori($slug)
    {
        $kategori = Category::withCount('product')->get();

        $produk = Category::where('slug',$slug)->first()->product()->orderBy('created_at','desc')->paginate(12);

        return view('produk.index',compact('produk','kategori'));
    }

    public function cari(Request $request)
    {
        $cari = $request->cari;

        $produk = Product::where('name','like',"%".$cari."%")->paginate(12);
        $kategori = Category::withCount('product')->get();


        // if($cari !== $produk)
        // {
        //     alert()->error('Tidak Ditemukan!', 'Produk');

        //     return redirect()->route('produk.admin');
        // }

        return view('produk.index',compact('produk','kategori'));
    }
}

resources/views/produk/detail.blade.php
@extends('layouts.app')
@section('title',$produk->name)

@section('content')

<div class="container mt-5">

    <nav aria-label="breadcrumb white">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{ route('home.index') }}">Home</a></li>
          <li class="breadcrumb-item"><a href="{{ route('produk.index') }}">Produk</a></li>
          <li class="breadcrumb-item active" aria-current="page">Produk Detail</li>
        </ol>
      </nav>

    <div class="row mt-5">
        <div class="col-12 col-sm-12 col-md-6 col-lg-6">
            <img src="{{ url('/storage/'.$produk->image) }}" style="width: 100%; height: 30vw; padding: 0"
                class="card-img-top" alt="...">
        </div>
        <div class="col-12 col-sm-12 col-md-6 col-lg-6">


            <h3><strong>{{ $produk->name }}</strong></h3>
            <h5>Rp. {{ number_format($produk->price,0,",","." )}}</h5>

            <table class="table mt-2">
                <tbody>
                    <tr>
                        <th scope="row">Status</th>
                        <td>:</td>
                        <td>
                            @if ($produk->quantity == 0)
                            <span class="badge badge-danger">Habis</span>
                            @else
                            <span class="badge badge-success">Tersedia</span>
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Kategori</th>
                        <td>:</td>
                        <td>{{ $produk->category['name'] }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Stok</th>
                        <td>:</td>
                        <td>{{ $produk->quantity }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Jumlah</th>
                        <td>:</td>
                        <td>
                            <form action="{{ route('tambahkeranjang.index',['slug'=>$produk->slug]) }}" method="post">
                                @csrf
                                <input type="text" class="form-control text-center" name="total" value="1">
                        </td>
                    </tr>
                </tbody>
            </table>
            @unlessrole('admin')
                <button type="submit" class="btn btn-primary w-100 mt-2"> <i class="fa fa-shopping-cart mr-2"></i> Tambah
                Keranjang</button>
            @endunlessrole
            </form>

            <nav class="mt-5">
                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                  <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Deskripsi</a>
                </div>
              </nav>
              <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                    <div class="container">
                        <p class="pt-2">
                            {{ $produk->desc }}
                        </p>
                    </div>
                </div>
              </div>
        </div>
    </div>

</div>

@endsection

resources/views/produk/index.blade.php
@extends('layouts.app')
@section('title','Produk')

@section('content')

<div class="container mt-5">
    <div class="wrapper-produk">
        <div class="row">
            <div class="col-12 col-md-3 col-lg-3">
                <h3 class="font-weight-bold">Kategori</h3>
                <div class="card mt-5">
                    @php
                        $all = App\Product::all()->count();
                    @endphp
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <a class="{{ set_active('produk.index') }}" href="{{ route('produk.index') }}">Semua</a>
                            <span class="badge badge-dark float-right">{{ $all }}</span>
                        </li>
                        @foreach($kategori as $kat)
                            <li class="list-group-item">
                                <a class="{{ set_active('produkkategori.index*') }}"
                                    href="{{ route('produkkategori.index',['slug'=>$kat->slug]) }}">{{ $kat->name }}</a>
                                <span class="badge badge-dark float-right">{{ $kat->product_count }}</span>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
            <div class="col-12 col-md-9 col-lg-9">
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-8 col-lg-8">
                        <h3 class="font-weight-bold">Produk</h3>

                    </div>
                </div>
                <div class="row mt-5">
                    @foreach($produk as $no => $data)
                        <div class="col-12 col-sm-6 col-lg-4 col-md-4 mb-4 card-product">
                            <a
                                href="{{ route('detailproduk.index',['slug'=>$data->slug]) }}">
                                <div class="card">
                                    <img src="{{ url('/storage/'.$data->image) }}"
                                        class="card-img-top" alt="...">
                                    <div class="card-body">

                                            <h5 class="card-title"><strong>{{ $data->name }}</strong></h5>

                                        <p class="card-text">Rp.
                                            {{ number_format($data->price,0,",",".") }}
                                        </p>
                                        <p class="card-text">{{ $data->category['name'] }}</p>
                                        {{-- <p class="card-text">{{ $data->created_at->diffForHumans() }}</p> --}}
                                    </div>
                                </div>
                            </a>
                        </div>
                    @endforeach
                </div>
                <div class="mt-3">
                    {{ $produk->links() }}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/produk/kategori.blade.php
@extends('layouts.app')
@section('title','Produk')

@section('content')

<div class="container">
    <div class="wrapper-produk">
        <div class="row">
            <div class="col-12 col-md-3 col-lg-3">
                <h3 class="font-weight-bold">Kategori</h3>
                    <div class="card mt-5">
                        <form action="{{ route('cariproduk.index') }}" method="get">
                            <div class="input-group">
                                <input type="text" name="cari" class="form-control" placeholder="Cari Produk..." id="">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                            </div>
                        </form>
                        @php
                            $all = App\Product::all()->count();
                        @endphp
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <a href="{{ route('produk.index') }}">Semua</a>
                                <span class="badge badge-dark float-right">{{ $all }}</span>
                            </li>
                            @foreach ($kategori as $kat)
                            <li class="list-group-item">
                                <a href="{{ route('produkkategori.index',['slug'=>$kat->slug]) }}">{{ $kat->name }}</a>
                                <span class="badge badge-dark float-right">{{ $kat->product_count }}</span>
                            </li>
                            @endforeach
                        </ul>
                    </div>
            </div>
            <div class="col-12 col-md-9 col-lg-9">
                <h3 class="font-weight-bold">{{ $prod->name }}</h3>
                <div class="row mt-5">
                    @foreach ($produk as $no => $data)
                    <div class="col-12 col-lg-4 col-md-4 col-sm-6 mb-4">
                        <div class="card">
                            <a href="{{ route('detailproduk.index',['slug'=>$data->slug]) }}">
                                <img src="{{ url('/storage/'.$data->image) }}" class="card-img-top" alt="...">
                            </a>
                            <div class="card-body">
                                <a href="{{ route('detailproduk.index',['slug'=>$data->slug]) }}">
                                    <h5 class="card-title">{{ $data->name }}</h5>
                                </a>
                                <p class="card-text">Rp. {{number_format($data->price,0,",",".")}}</p>
                                <p class="card-text">{{$data->category['name']}}</p>
                                <p class="card-text">{{$data->created_at->diffForHumans()}}</p>
                            </div>
                        </div>
                    </div>
                    @endforeach
                </div>
                <div class="mt-3">
                    {{ $produk->links() }}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection